// // API ENDPOINTS USER //

// HÄMTA ALLA USERS
GET http://localhost:3000/users

###

// SKAPA USER
POST http://localhost:3000/users/add
Content-Type: application/json

{
  "name": "bamse",
  "email": "johnDoe@mail.com",
  "password": "test"
}

###

// LOGGA IN USER
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "noah@hotmail.com",
  "password": "test"
}

###
// HÄMTA USER DOCUMENTS
POST http://localhost:3000/documents
Content-Type: application/json

{
  "userId": "a0715001-37b5-42bd-a6f0-c30a85dc06af"
}

###
// SKAPA USER DOCUMENT
POST http://localhost:3000/documents/add
Content-Type: application/json

{
  "name":"document1",
  "content":"<p>hej</p>",
  "userId": "a0715001-37b5-42bd-a6f0-c30a85dc06af"
}