// // API ENDPOINTS USER //

// HÄMTA ALLA USERS
GET http://localhost:3000/users

###

// SKAPA USER
POST http://localhost:3000/users/add
Content-Type: application/json

{
  "name": "bamse",
  "email": "johnDoe@mail.com",
  "password": "test"
}

###

// LOGGA IN USER
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "noah@hotmail.com",
  "password": "test"
}

###
// HÄMTA USER DOCUMENTS
POST http://localhost:3000/documents
Content-Type: application/json

{
  "userId": "a0715001-37b5-42bd-a6f0-c30a85dc06af"
}

###
// SKAPA USER DOCUMENT
POST http://localhost:3000/documents/add
Content-Type: application/json

{
  "name":"document1",
  "content":"<h1>hej</h1><p>då</p>",
  "userId": "b25ca010-e13c-447e-93fe-9cbb130214de"
}

###
// SOFT DELETA DOCUMENT
PUT http://localhost:3000/documents/delete
Content-Type: application/json

{
  "id": 7
}
//för att"ångra" skriv följande sql query i myAdminPhp: UPDATE documents SET deleted = false WHERE id = '7'